Update install-x

diff --git a/install-x b/install-x
--- a/install-x
+++ b/install-x
@@ -23,37 +23,8 @@ echo ""
 
 sleep 1
 
-while true; do
-  read -p "Do you want to install X for chromebooks, this was developed by 2 highschool students? [y/n]" yn
-  case $yn in
-  [yY]* ) break;;
-  [nN]* ) exit;;
-  * ) echo "Please type y or n";; 
-  esac
-done
-
-#Similar to chromebrew check to see if architecture is similar
-user=$(whoami)
-architecture=$(uname -m)
-
-if [ $architecture != "i686" ] && [ $architecture != "x86_64" ]; then
-  echo "Please make sure you have an intel 32bit or 64bit device for Crevos to work :'("
-  echo 'exiting...'
-  exit 1;
-fi
-
-echo "The problem here is that we can't just randomly change deep system files"
-echo "we will need to remount the user filesystem so we can edit the X11 settings"
-
-while true; do
-  read -p "Have you mounted and rebooted your syetem to read and write yet? [y/n]" ynn
-  case $ynn in
-  [yY]* ) GOING=1; break;;
-  [nN]* ) break;;
-  * ) echo "Please type y or n";; 
-  esac
-done
-if [$GOING = 0]; then
+runs()
+{
   echo "Please be ready to anwser system settings questions, so that we can proceed"
   sleep 3
   sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification
@@ -82,7 +53,39 @@ if [$GOING = 0]; then
   [nN]* ) exit;;
   * ) echo "Sorry didn't understand that :'(";; 
   esac
+}
+
+
+while true; do
+  read -p "Do you want to install X for chromebooks, this was developed by 2 highschool students? [y/n]" yn
+  case $yn in
+  [yY]* ) break;;
+  [nN]* ) exit;;
+  * ) echo "Please type y or n";; 
+  esac
+done
+
+#Similar to chromebrew check to see if architecture is similar
+user=$(whoami)
+architecture=$(uname -m)
+
+if [ $architecture != "i686" ] && [ $architecture != "x86_64" ]; then
+  echo "Please make sure you have an intel 32bit or 64bit device for Crevos to work :'("
+  echo 'exiting...'
+  exit 1;
 fi
+
+echo "The problem here is that we can't just randomly change deep system files"
+echo "we will need to remount the user filesystem so we can edit the X11 settings"
+
+while true; do
+  read -p "Have you mounted and rebooted your syetem to read and write yet? [y/n]" ynn
+  case $ynn in
+  [yY]* ) runs;break;;
+  [nN]* ) break;;
+  * ) echo "Please type y or n";; 
+  esac
+done
 
 echo 'Attempting to install X'
 sleep 2
