Update install-x

diff --git a/install-x b/install-x
--- a/install-x
+++ b/install-x
@@ -42,8 +42,34 @@ if [ $architecture != "i686" ] && [ $architecture != "x86_64" ]; then
   exit 1;
 fi
 
-echo 'Installing X'
-sleep 4
+echo "The problem here is that we can't just randomly change deep system files"
+echo "we will need to remount the user filesystem so we can edit the X11 settings"
+echo "Please be ready to anwser system settings questions, so that we can proceed"
+sleep 3
+sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification
+sudo crossystem dev_boot_signed_only=0
+sleep 1
+echo ""
+echo ""
+echo "I just ran a script to modify your kernel, so I can access system directories..."
+echo "The above command I just ran said 'Try running the script with ...... --partitions N'"
+echo ""
+echo ""
+read -p "Please enter (The number nothing else ex: 2) the number of the partition N above: " an
+re='^[0-9]+$'
+if ! [[ $an =~ $re ]] ; then
+   echo "error: Not a number... restart amazing script with install-x" >&2; exit 1
+fi
+sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions $an
+sudo crossystem dev_boot_signed_only=0
+sudo mount -o remount,rw /
+echo "Succesful remount of system, now the rest of the script should run with little warnings besides"
+echo "That this isn't a officialy supported device (Luckily we have been able to fix that)"
+
+sleep 2
+
+echo 'Attempting to install X'
+sleep 2
 cd $CPACKAGES
 
 wget -N --continue --no-check-certificate $URL/packages/twm.rb
